// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("apz.overscroll.enabled", true);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.cache.disk.amount_written", 775361);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.parent_directory", "/run/user/1000/firefox");
user_pref("browser.contentblocking.category", "custom");
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.search.hiddenOneOffs", "Amazon.com.au,Bing,Chambers (UK),eBay,Google,Wikipedia (en)");
user_pref("browser.search.region", "AU");
user_pref("browser.search.update", false);
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage", "/home/mirror/usr/startpage/index.html");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uidensity", 1);
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.inspector.activeSidebar", "ruleview");
user_pref("devtools.inspector.three-pane-enabled", false);
user_pref("devtools.layout.grid.opened", false);
user_pref("devtools.toolbox.host", "right");
user_pref("devtools.toolbox.previousHost", "bottom");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 500);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 201);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "80.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.recommendations.hideNotice", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("findbar.highlightAll", true);
user_pref("font.internaluseonly.changed", true);
user_pref("font.name.monospace.x-western", "Roboto Mono");
user_pref("font.name.serif.x-western", "DejaVu Sans");
user_pref("font.size.monospace.x-western", 13);
user_pref("full-screen-api.warning.timeout", 0);
user_pref("general.autoScroll", true);
user_pref("general.smoothScroll.durationToIntervalRatio", 50);
user_pref("general.smoothScroll.lines.durationMaxMS", 30);
user_pref("general.smoothScroll.lines.durationMinMS", 30);
user_pref("general.smoothScroll.mouseWheel.durationMaxMS", 90);
user_pref("general.smoothScroll.mouseWheel.durationMinMS", 90);
user_pref("general.smoothScroll.other.durationMaxMS", 30);
user_pref("general.smoothScroll.other.durationMinMS", 20);
user_pref("general.smoothScroll.pages.durationMaxMS", 30);
user_pref("general.smoothScroll.pages.durationMinMS", 20);
user_pref("general.smoothScroll.pixels.durationMaxMS", 30);
user_pref("general.smoothScroll.pixels.durationMinMS", 20);
user_pref("middlemouse.paste", false);
user_pref("mousewheel.min_line_scroll_amount", 30);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 100207);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.popups.showBrowserMessage", false);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("privacy.trackingprotection.pbmode.enabled", false);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.sync.clients.devices.desktop", 1);
user_pref("services.sync.clients.devices.mobile", 1);
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.deletePwdFxA", true);
user_pref("services.sync.engine.prefs.modified", false);
user_pref("services.sync.globalScore", 100);
user_pref("services.sync.prefs.sync.browser.tabs.warnOnClose", false);
user_pref("services.sync.syncInterval", 600000);
user_pref("services.sync.syncThreshold", 300);
user_pref("storage.vacuum.last.index", 1);
user_pref("svg.context-properties.content.enabled", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.key.menuAccessKey", 0);
user_pref("ui.key.menuAccessKeyFocuses", false);
user_pref("widget.content.gtk-theme-override", "Adwaita:Light");
