#!/usr/bin/env bash

[ "$1" = -y ] &&
	y=y

echo
echo "This is made for me, and me alone, please do not
expect this to work on your system, and do not complain
that this doesn't work on your system.
I am not responsible for your system breaking
if you proceed any further."
echo

printf '[Make sure this repository is installed as ~/opt/dots, then hit y] '
read -r y
[[ $y = y ]] || exit

mkdir -p ~/bin ~/etc ~/usr/cache ~/opt 2>/dev/null

for i in $(dirname $HOME/opt/dots/*/bin | sed "s|$HOME/opt/dots/||"); do
	mkdir $HOME/bin/$i
	ln -s $HOME/opt/dots/$i/bin/* $HOME/bin/$i/
done
ln -sf $HOME/opt/dots/*/etc/* ~/etc/ 2>/dev/null
ln -sf $HOME/opt/dots/*/usr/* ~/usr/ 2>/dev/null
