#!/bin/sh

if [ "$1" = y ]; then
	y=y
else
	printf '[press the damn button, fool] '
	read -r y
fi

[ "$y" = y ] || exit

mkdir -p      \
	~/bin/app   \
	~/bin/bin   \
	~/etc       \
	~/usr/cache \
	~/opt 2>/dev/null

ln -sf "$PWD/bin/"* ~/bin/ 2>/dev/null
ln -sf "$PWD/etc/"* ~/etc/ 2>/dev/null
ln -sf "$PWD/usr/"* ~/usr/ 2>/dev/null
