#!/bin/sh
#
#  bspwmrc
#


# desktops
bspc monitor -d                    1 2 3 4 5 6
bspc monitor DVI-D-0 -d            7 8 9 10


# mouse
xsetroot    -cursor_name           left_ptr
bspc config pointer_modifier       mod1

bspc config focus_follows_pointer  true
bspc config pointer_follows_focus  false


# borders/gaps
bspc config window_gap             40
bspc config gapless_monocle        true

bspc config border_width           0
bspc config borderless_monocle     true
bspc config normal_border_color    "#19191C"
bspc config focused_border_color   "#202026"


# other
bspc config single_monocle         true


#
#   rules
#
bspc rule -a feh                   state=floating
bspc rule -a tabbed                state=floating
bspc rule -a Gcolor3               state=floating
