#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/gauge/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

compton &
nm-applet &
#yakuake &
#xfce4-panel &
#latte-dock &
feh --bg-fill "/home/gauge/Wallpapers/Hexagon Krayons.png"
#lxqt-panel &
#lxqt-notificationd &
volumeicon &
pnmixer &
xautolock -time 10 -locker ~/bin/lock &
kglobalaccel5 &
albert &
tint2 -c /home/gauge/.config/tint2/topleft.tint2rc &
tint2 -c /home/gauge/.config/tint2/topright.tint2rc &
conky &
dunst &
#cbatticon --command-left-click "battery" &

yakuake &


exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/gauge/.fluxbox/log"
