#!/bin/sh
#
#   Tweaks
#

wm="${1:-bspwm}"
c="${XDG_CONFIG_HOME:=$HOME/.config}"

# Basic X stuff
#for f in /etc/X11/xinit/xinitrc.d/*.sh; do
#	. "$f"
#done; f=

# DBus
[ "$DBUS_SESSION_BUS_ADDRESS" ] ||
	dbus-launch --exit-with-session "$c/xinitrc" "$@" &

pap        # wallpaper
hw 0       # clear hidden windows cache
rmd &      # remove annoying files that keep appearing in ~
screen.sh  # change display layout
xset r rate 200 60   &   # faster keyboard
xmousepasteblock     &   # disable middle-click paste
unclutter -idle 15   &   # hide cursor after 15 seconds
synclient TouchpadOff=1  # disable touchpad
nice -n 10 pulseaudio -D &          # audio
xrdb "$c/Xresources"

case "$wm" in
	bspwm) ;;  # already in the config
	gnome) export XDG_SESSION_TYPE=x11 GDK_BACKEND=x11 wm=gnome-session;;
	kde) wm=startplasma-x11;;
	*)  sxhkd &  picom &  dunst &
esac

D() {
xmodmap - << EOF
	clear lock
	clear control
	keycode 37 =
	add control = Control_L Control_L Control_R
	keycode 66 = Control_L Control_L NoSymbol NoSymbol
EOF
};D;D  # doesn't work if it's only ran once...

exec "$wm"
