#!/bin/sh
#
#   Tweaks
#

# Basic X stuff
for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
	[ -x "$f" ] && . "$f"
done
unset f

# bind caps lock to control, make l_ctrl do nothing
cat << EOF | xmodmap /dev/stdin
	clear lock
	clear control
	keycode 37 =
	add control = Control_L Control_L Control_R
	keycode 66 = Control_L Control_L NoSymbol NoSymbol
EOF
xmousepasteblock

# DBus
if [ ! "$DBUS_SESSION_BUS_ADDRESS" ]; then
	dbus-launch --exit-with-session "${XDG_CONFIG_HOME:-~/.config}/xinitrc" "$@" &
fi


screen.sh     # Custom screen layout
pap           # Wallpaper

synclient TouchpadOff=1           # Disable touchpad
xset r rate 200 60 &              # Faster keyboard

xrdb "${XDG_CONFIG_HOME:-~/.config}/Xresources"

unclutter -idle 15     &
start-pulseaudio-x11   &

hw 0

#sxhkd &
#picom &
#dunst &

#
#   And finally, start the window manager
#

exec "${1:-bspwm}"
