#!/bin/sh

#
#   Tweaks
#

# Basic X stuff
for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
	[ -x "$f" ] && . "$f"
done
unset f

# DBus
if [[ ! "$DBUS_SESSION_BUS_ADDRESS" ]]; then
	dbus-launch --exit-with-session ${XDG_CONFIG_HOME:-~/.config}/xinitrc "$@" &
fi


pap           # Wallpaper
screen.sh     # Custom screen layout

synclient TouchpadOff=1           # Disable touchpad
xset r rate 200 60 &              # Faster keyboard

xrdb ${XDG_CONFIG_HOME:-~/.config}/Xresources

unclutter -idle 15     &
start-pulseaudio-x11   &

#
#   And finally, start the window manager
#

exec bspwm
