#!/bin/sh

#     --
#   Tweaks
#     --

# Basic X stuff
[ -d /etc/X11/xinit ] && (
for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
	[ -x "$f" ] && . "$f"
done
unset f)

# DBus
if [[ ! "$DBUS_SESSION_BUS_ADDRESS" ]]; then
	dbus-launch --exit-with-session ${XDG_CONFIG_HOME:-~/.config}/xinitrc "$@" &
fi


pap           # Wallpaper
screen.sh     # Custom screen layout

synclient TouchpadOff=1           # Disable touchpad
xset r rate 200 60 &              # Faster keyboard
xsetroot -cursor_name left_ptr    # Make desktop use normal cursor

xrdb ${XDG_CONFIG_HOME:-~/.config}/Xresources

#       ----
#   Applications
#       ----

dunst &    # Notification daemon
sxhkd &    # Hotkey daemon
compton &  # compositor
recom &    # restart compton every once in a while

start-dropdown.sh &


#                   ----
#   And finally, start the window manager
#                   ----

exec bspwm
