#!/bin/sh
#
#   Tweaks
#

wm="${1:-bspwm}"
c="${XDG_CONFIG_HOME:=$HOME/.config}"

# /etc/X11/xinit/xinitrc.d/*.sh
# [ "$DBUS_SESSION_BUS_ADDRESS" ] || dbus-launch --exit-with-session ...

dsync init &
hw 0       & # clear hidden windows cache
screen.sh    # change display layout
pap        & # wallpaper
clipwatch  &
xmousepasteblock     &   # disable middle-click paste
unclutter -idle 15   &   # hide cursor after 15 seconds
synclient TouchpadOff=1  # disable touchpad
xrdb "$c/xorg/res" &

case "$wm" in
	bspwm) ;;  # already in the config
	gnome) export XDG_SESSION_TYPE=x11 GDK_BACKEND=x11 wm=gnome-session;;
	kde) wm=startplasma-x11;;
	xfce) wm=startxfce4; sxhkd &;;
	*)  sxhkd &  picom &  dunst &
esac

{  # keyboard mapping | git.io/kmonad
	sleep 3
	sudo kmonad ~/opt/dots/opt/keyboard.kbd & #sleep 2; xset r rate 200 60
} &

{ sleep 5; qbittorrent; } &

"$wm"
