#!/usr/bin/env sh
#
#  bspwmrc
#
# yes, using env rather than a direct /bin/sh is intentional,
# but I won't say the reason :)

c() { bspc config "$@" &  }
R() { bspc rule -a "$@" & }
s() { pkill -x "$1"; { sleep 0.1; "$@" & }; }
sx=$XDG_CONFIG_HOME/sxhkd  bs=$XDG_CONFIG_HOME/bspwm

# desktops
bspc monitor -d      1 2 3 4 5 6
bspc monitor DVI-D-0 -d  7 8 9 0
# fix ordering
bspc monitor DVI-D-0 -s HDMI-0

c ignore_ewmh_fullscreen all
#c ignore_ewmh_focus true

# mouse
xsetroot -cursor_name      left_ptr
c pointer_modifier         mod4
c focus_follows_pointer    true
c pointer_follows_focus    false
c pointer_motion_interval  5


# borders/gaps
c window_gap    15
c border_width  0
c single_monocle      true
c gapless_monocle     true
c borderless_monocle  true

c normal_border_color       '#222242'
c active_border_color       '#222242'
c focused_border_color      '#222242'


#
#   rules
#
R taskman   locked=on
R yeetfocus state=floating focus=on rectangle=1x1+1+1 border=off
R obs       desktop=6
R Steam     desktop=5
R feh       state=floating
R tabbed    state=floating
R Gcolor3   state=floating
R floating  state=floating
R menu      state=floating sticky=on layer=normal
R freeze    state=floating border=off monitor=HDMI-0 layer=above focus=off
R Surphace  state=floating border=off rectangle=3360x3024+0+0
R conky     state=floating layer=above sticky=true focus=off manage=off
R Dragon    sticky=true
R qBittorrent desktop=5
R qbittorrent desktop=5


#
#   autostart
#
pgrep sxhkd || {
	# focus first/last desktops
	bspc desktop -f ^10 -f ^1

	## dropdown htop/shell
	# start invisible
	bspc rule -a taskman hidden=on -o
	st -c taskman -e bash -c 'while :; do sudo -E htop; zsh; done' &

	# on reboots stuff sometimes takes a while to start
	sleep 5

	# pid > xdotool wid > wmutils wid
	printf 0x%x "$(xdotool search --pid $!)" > "$XDG_CACHE_HOME/hw/1"
} &

s picom
s dunst
#s swallow
s borders
s sxhkd -c "$sx/other"  # give priority to binds in this file
sxhkd -c "$sx/sxhkdrc"  "$sx/bspwm"
[ -e "$bs/other" ] && . "$bs/other"
