#!/bin/sh
#
#   ┏━━━━━━━┓
#   ┃ bspwm ┃
#   ┗━━━━━━━┛
#

bspc monitor -d 1 2 3 4 5 6
bspc monitor DVI-D-0 -d 7 8 9 10

bspc config window_gap 40
bspc config border_width 0
bspc config border_radius 7

xsetroot -cursor_name left_ptr
bspc config pointer_modifier mod1

bspc config single_monocle true
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config normal_border_color "#a6a9b7"
bspc config focused_border_color "#daddee"
bspc config presel_feedback_color "#eeeeee"

#       ----
#   Window Rules
#       ----

bspc rule -a feh state=floating
bspc rule -a qView state=floating
bspc rule -a tabbed state=floating
bspc rule -a Thunar state=floating
bspc rule -a dolphin state=floating
bspc rule -a Gcolor3 state=floating
bspc rule -a floating state=floating
bspc rule -a ksysguard state=floating


bar &
