#!/bin/sh
v=$(who)
user=${v%% *}
uid=$(id -u "$user")

out=$(printf "%s\n%s\n" "$ID_VENDOR" "$ID_MODEL" | tr '_' ' ')

export DISPLAY="${display:-:0}" XDG_RUNTIME_DIR=/run/user/"$uid" \
	DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/"$uid"/bus \

sudo -Eu "$user" /usr/bin/notify-send "New device detected" "$out"
sudo -Eu "$user" /usr/bin/paplay /usr/local/sounds/usb-insert.wav
