#!/bin/sh
#
# wm config

# ---
# settings
# ---

bspc monitor -d 1 2 3 4 5

while read -r line; do
    test "$line" && bspc config $line
done << EOF
external_rules_command ~/.local/bin/rules

focus_follows_pointer true
borderless_monocle true
gapless_monocle true
single_monocle true

presel_feedback_color #EEEEEE
focused_border_color #ee99ff
normal_border_color #252c3f

border_width 3
window_gap 6
EOF

# ---
# utils
# ---

#for bin in panel borders; do
#    pgrep -x "$bin" > /dev/null || "$bin" &
#done

bspc rule -a tabbed state=floating
bspc rule -a dolphin state=floating
bspc rule -a qview state=floating
bspc rule -a ksysguard state=floating
