#!/bin/sh

#     ---
#   Settings
#     ---

bspc config window_gap 10
bspc config border_width 0
bspc config border_radius 7

bspc monitor -d 1 2 3 4 5
bspc monitor DVI-D-0 -d 6 7

bspc config pointer_modifier mod1

bspc config single_monocle true
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config normal_border_color "#111c23"
bspc config focused_border_color "#f6b2b6"
bspc config presel_feedback_color "#eeeeee"

#       ----
#   Window Rules
#       ----

bspc rule -a qView state=floating
bspc rule -a tabbed state=floating
bspc rule -a dolphin state=floating
bspc rule -a floating state=floating
bspc rule -a ksysguard state=floating
